export enum CatalogActions  {

   CATALOG_LIST_ALL_TESTS_FROM_API = "@@labCatalog/LIST_ALL_TESTS_FROM_API",
   CATALOG_LIST_ALL_TESTS_FROM_API_FETCHING = "@@labCatalog/LIST_ALL_TESTS_FROM_API_FETCHING",
   CATALOG_LIST_ALL_TESTS_FROM_API_SUCCESS = "@@labCatalog/LIST_ALL_TESTS_FROM_API_SUCCESS",
   CATALOG_LIST_ALL_TESTS_FROM_API_ERROR = "@@labCatalog/CATALOG_LIST_ALL_TESTS_FROM_API_ERROR",



   /** Catalog Operations Actions  */

   // fetch existing catalog from labTest
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS',
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_ERROR = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_ERROR',
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_SUCCESS = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_SUCCESS',

   // Add Catalog List Test
   CATALOG_LIST_TESTS_NEW_TEST = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST",

   // fetch all tests lab from server
   CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS            = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS",
    CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_FETCHING   = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_FETCHING",
     CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_SUCCESS    = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_SUCCESS",
      CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_ERROR      = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_ERROR",

   // Select Catalog List 
   CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST            = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST",
    CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_ERROR      = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_ERROR",
     CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_SUCCESS    = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_SUCCESS",

   // Filter catalog list
   CATALOG_LIST_FILTER_TEST_TEST             = "@@labCatalog/CATALOG_LIST_FILTER_TEST_TEST",
    CATALOG_LIST_FILTER_TEST_NAME             = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME",
     CATALOG_LIST_FILTER_TEST_NAME_ERROR       = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME_ERROR",
      CATALOG_LIST_FILTER_TEST_NAME_SUCCESS     = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME_SUCCESS",

   // Save catalog one test
   CATALOG_LIST_UPDATE_TEST_BY_USER          = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER",
    CATALOG_LIST_UPDATE_TEST_BY_USER_BEGIN     = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_BEGIN",
     CATALOG_LIST_UPDATE_TEST_BY_USER_ERROR       = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_ERROR",
      CATALOG_LIST_UPDATE_TEST_BY_USER_SUCCESS       = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_SUCCESS",

   // existing catalog
   CATALOG_LIST_UPDATE_FETCH           = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH",
    CATALOG_LIST_UPDATE_FETCH_SUCCESS   = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_SUCCESS",
     CATALOG_LIST_UPDATE_FETCH_ERROR     = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_ERROR",
      CATALOG_LIST_UPDATE_FETCH_BEGIN     = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_BEGIN",

   // User update catalog list
   CATALOG_LIST_UPDATING_BY_USER       = "@@labCatalog/CATALOG_LIST_UPDATING_BY_USER",
    CATALOG_LIST_UPDATING_SAVE          = "@@labCatalog/CATALOG_LIST_UPDATING_SAVE",
     CATALOG_LIST_UPDATING_MODAL_CLOSE   = "@@labCatalog/CATALOG_LIST_UPDATING_MODAL_CLOSE"
}