export enum CatalogActions  {

   CATALOG_LIST_ALL_TESTS_FROM_API = "@@labCatalog/LIST_ALL_TESTS_FROM_API",
   CATALOG_LIST_ALL_TESTS_FROM_API_FETCHING = "@@labCatalog/LIST_ALL_TESTS_FROM_API_FETCHING",
   CATALOG_LIST_ALL_TESTS_FROM_API_SUCCESS = "@@labCatalog/LIST_ALL_TESTS_FROM_API_SUCCESS",
   CATALOG_LIST_ALL_TESTS_FROM_API_ERROR = "@@labCatalog/CATALOG_LIST_ALL_TESTS_FROM_API_ERROR",



   /** fetch all existing catalogs  */
   CATALOG_FETCH_ALL = '@@labCatalog/CATALOG_FETCH_ALL',
    CATALOG_FETCH_ALL_ERROR = '@@labCatalog/CATALOG_FETCH_ALL_ERROR',
      CATALOG_FETCH_ALL_SUCCESS = '@@labCatalog/CATALOG_FETCH_ALL_SUCCESS',

   /** Catalog fetch selected details  */
   CATALOG_FETCH_DETAILS = '@@labCatalog/CATALOG_FETCH_DETAILS',
    CATALOG_FETCH_DETAILS_ERROR = '@@labCatalog/CATALOG_FETCH_DETAILS_ERROR',
      CATALOG_FETCH_DETAILS_SUCCESS = '@@labCatalog/CATALOG_FETCH_DETAILS_SUCCESS',
   
   /** Catalog update bfactor */
   CATALOG_UPDATE_BFACTOR = '@@labCatalog/CATALOG_UPDATE_BFACTOR',
    CATALOG_UPDATE_BFACTOR_ERROR = '@@labCatalog/CATALOG_UPDATE_BFACTOR_ERROR',
      CATALOG_UPDATE_BFACTOR_SUCCESS = '@@labCatalog/CATALOG_UPDATE_BFACTOR_SUCCESS',
      
   /** Catalog update bfactor */
   CATALOG_UPDATE_PRICE = '@@labCatalog/CATALOG_UPDATE_PRICE',
    CATALOG_UPDATE_PRICE_ERROR = '@@labCatalog/CATALOG_UPDATE_PRICE_ERROR',
      CATALOG_UPDATE_PRICE_SUCCESS = '@@labCatalog/CATALOG_UPDATE_PRICE_SUCCESS',
   /** Catalog update referred */
   CATALOG_UPDATE_REFERRED = '@@labCatalog/CATALOG_UPDATE_REFERRED',
    CATALOG_UPDATE_REFERRED_ERROR = '@@labCatalog/CATALOG_UPDATE_REFERRED_ERROR',
      CATALOG_UPDATE_REFERRED_SUCCESS = '@@labCatalog/CATALOG_UPDATE_REFERRED_SUCCESS',
   
   /** Catalog fetch modified tests  */
   CATALOG_FETCH_MODIFIED_TESTS = '@@labCatalog/CATALOG_FETCH_MODIFIED_TESTS',
    CATALOG_FETCH_MODIFIED_TESTS_ERROR = '@@labCatalog/CATALOG_FETCH_MODIFIED_TESTS_ERROR',
      CATALOG_FETCH_MODIFIED_TESTS_SUCCESS = '@@labCatalog/CATALOG_FETCH_MODIFIED_TESTS_SUCCESS',
   

   // fetch existing catalog from labTest
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS',
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_ERROR = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_ERROR',
   CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_SUCCESS = '@@labCatalog/CATALOG_LIST_FETCH_TESTS_FROM_LABTESTS_SUCCESS',

   // Add Catalog List Test
   CATALOG_LIST_TESTS_NEW_TEST = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST",

   // fetch all tests lab from server
   CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS            = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS",
    CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_FETCHING   = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_FETCHING",
     CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_SUCCESS    = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_SUCCESS",
      CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_ERROR      = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_FETCH_TESTS_ERROR",

   // Select Catalog List 
   CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST            = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST",
    CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_ERROR      = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_ERROR",
     CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_SUCCESS    = "@@labCatalog/CATALOG_LIST_TESTS_NEW_TEST_SELECT_TEST_SUCCESS",

   // Filter catalog list
   CATALOG_LIST_FILTER_TEST_TEST             = "@@labCatalog/CATALOG_LIST_FILTER_TEST_TEST",
    CATALOG_LIST_FILTER_TEST_NAME             = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME",
     CATALOG_LIST_FILTER_TEST_NAME_ERROR       = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME_ERROR",
      CATALOG_LIST_FILTER_TEST_NAME_SUCCESS     = "@@labCatalog/CATALOG_LIST_FILTER_TEST_NAME_SUCCESS",

   // Save catalog one test
   CATALOG_LIST_UPDATE_TEST_BY_USER          = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER",
    CATALOG_LIST_UPDATE_TEST_BY_USER_BEGIN     = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_BEGIN",
     CATALOG_LIST_UPDATE_TEST_BY_USER_ERROR       = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_ERROR",
      CATALOG_LIST_UPDATE_TEST_BY_USER_SUCCESS       = "@@labCatalog/CATALOG_LIST_UPDATE_TEST_BY_USER_SUCCESS",

   // existing catalog
   CATALOG_LIST_UPDATE_FETCH           = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH",
    CATALOG_LIST_UPDATE_FETCH_SUCCESS   = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_SUCCESS",
     CATALOG_LIST_UPDATE_FETCH_ERROR     = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_ERROR",
      CATALOG_LIST_UPDATE_FETCH_BEGIN     = "@@labCatalog/CATALOG_LIST_UPDATE_FETCH_BEGIN",

   // User update catalog list
   CATALOG_LIST_UPDATING_BY_USER       = "@@labCatalog/CATALOG_LIST_UPDATING_BY_USER",
    CATALOG_LIST_UPDATING_SAVE          = "@@labCatalog/CATALOG_LIST_UPDATING_SAVE",
     CATALOG_LIST_UPDATING_MODAL_CLOSE   = "@@labCatalog/CATALOG_LIST_UPDATING_MODAL_CLOSE"
}