export enum SettingActions {

    // fetch departement
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT",
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_ERROR",
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_SUCCESS",

    // add departement
    LAB_LABO_SETTING_LIST_DEPARTEMENT = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT",
    LAB_LABO_SETTING_LIST_DEPARTEMENT_ERROR = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT_ERROR",
    LAB_LABO_SETTING_LIST_DEPARTEMENT_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT_SUCCESS",

    // fetch jf
    LAB_LABO_SETTING_LIST_HOLIDAY = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY",
    LAB_LABO_SETTING_LIST_HOLIDAY_ERROR = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY_ERROR",
    LAB_LABO_SETTING_LIST_HOLIDAY_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY_SUCCESS",

    // add jf
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY",
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY_ERROR",
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY_SUCCESS",

    // fetch CONGER
    LAB_LABO_SETTING_LIST_LEAVE = "@@setting/LAB_LABO_SETTING_LIST_LEAVE",
    LAB_LABO_SETTING_LIST_LEAVE_ERROR = "@@setting/LAB_LABO_SETTING_LIST_LEAVE_ERROR",
    LAB_LABO_SETTING_LIST_LEAVE_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_LEAVE_SUCCESS",

    // add CONGER
    LAB_LABO_SETTING_ADD_NEW_LEAVE = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE",
    LAB_LABO_SETTING_ADD_NEW_LEAVE_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE_ERROR",
    LAB_LABO_SETTING_ADD_NEW_LEAVE_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE_SUCCESS",

    // fetch automate
    LAB_LABO_SETTING_LIST_AUTOMATE = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE",
    LAB_LABO_SETTING_LIST_AUTOMATE_ERROR = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE_ERROR",
    LAB_LABO_SETTING_LIST_AUTOMATE_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE_SUCCESS",

    // add automate
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE",
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE_ERROR",
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE_SUCCESS",
    // add role
    LAB_LABO_SETTING_ADD_NEW_ROLE = "@@setting/LAB_LABO_SETTING_ADD_NEW_ROLE",
        LAB_LABO_SETTING_ADD_NEW_ROLE_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_ROLE_ERROR",
            LAB_LABO_SETTING_ADD_NEW_ROLE_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_ROLE_SUCCESS",
    // add role
    LAB_LABO_SETTING_DELETE_ROLE = "@@setting/LAB_LABO_SETTING_DELETE_ROLE",
        LAB_LABO_SETTING_DELETE_ROLE_ERROR = "@@setting/LAB_LABO_SETTING_DELETE_ROLE_ERROR",
            LAB_LABO_SETTING_DELETE_ROLE_SUCCESS = "@@setting/LAB_LABO_SETTING_DELETE_ROLE_SUCCESS",
    // fetch roles
    LAB_LABO_SETTING_LIST_ROLES = "@@setting/LAB_LABO_SETTING_LIST_ROLES",
        LAB_LABO_SETTING_LIST_ROLES_ERROR = "@@setting/LAB_LABO_SETTING_LIST_ROLES_ERROR",
            LAB_LABO_SETTING_LIST_ROLES_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_ROLES_SUCCESS",
    // fetch roles
    LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS = "@@setting/LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS",
        LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS_ERROR = "@@setting/LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS_ERROR",
            LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS_SUCCESS = "@@setting/LAB_LABO_SETTING_ROLE_UPDATE_PERMISSIONS_SUCCESS",

}